# Changes here will be overwritten by Copier
_commit: 0.1.0
_src_path: https://github.com/fastapi-mvc/copier-generator.git
copyright_date: 2022
generator: script
generator_name: script
license: MIT
nix: true
repo_url: https://your.repo.url.here
